// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLqtxHPUWbDjFsJhlVzN20jHiYcdVaTGQ',
    appId: '1:692388655160:web:d4fe237ab06b7b5e1fb6cd',
    messagingSenderId: '692388655160',
    projectId: 'tmchall-ef1fc',
    authDomain: 'tmchall-ef1fc.firebaseapp.com',
    storageBucket: 'tmchall-ef1fc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEu6tRknX5TkspHG_2cGEsa_Cc2mbf8qM',
    appId: '1:692388655160:android:2c83899e9649bcaa1fb6cd',
    messagingSenderId: '692388655160',
    projectId: 'tmchall-ef1fc',
    storageBucket: 'tmchall-ef1fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYgqx0fnqifq-W266UhoIYnqy9XG4fawk',
    appId: '1:692388655160:ios:ccb89410e1ac424e1fb6cd',
    messagingSenderId: '692388655160',
    projectId: 'tmchall-ef1fc',
    storageBucket: 'tmchall-ef1fc.firebasestorage.app',
    iosBundleId: 'com.example.tmchall',
  );
}
